# Generated by Django 5.0.1 on 2024-01-09 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='highest_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
