# Generated by Django 5.0.1 on 2024-01-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listings_highest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
