# Generated by Django 5.0.1 on 2024-01-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='winner_status',
            field=models.BooleanField(default=False),
        ),
    ]
