# Generated by Django 5.0.1 on 2024-01-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bids_winner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='highest_bid',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_bid', to='auctions.bids'),
        ),
    ]
