# Generated by Django 5.0.1 on 2024-01-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_comments_comment_alter_comments_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateField(auto_now_add=True, default='2014-1-10'),
            preserve_default=False,
        ),
    ]
