# Generated by Django 5.0.1 on 2024-01-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_comments_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'verbose_name_plural': 'Listings'},
        ),
    ]
